name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # ✅ Step 2: Set Up Docker Buildx
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ✅ Step 3: Log In to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log In to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # ✅ Step 4: Build and Push Docker Image to ECR
      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cat-dog-classifier
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # ✅ Step 5: Update AWS Lambda with the New Docker Image
      - name: Update AWS Lambda
        run: |
          aws lambda update-function-code --function-name cat-dog-classifier \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
